name: release-drafter

on:
  workflow_dispatch: {}

jobs:
  modulea-draft-release:
    name: Module A draft release
    runs-on: ubuntu-20.04
    steps:
      - uses: blast-hardcheese/release-drafter@v5.16.2
        with:
          tag-prefix: modulea-v
          include-paths: modules/module-a
          config-name: modulea-release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
